# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Trollfjord\Bundle\GlossaryBundle\Controller\:
    resource: '../../Controller/'
    tags: [ 'controller.service_arguments' ]

  Trollfjord\Bundle\GlossaryBundle\ControllerPublic\:
    resource: '../../ControllerPublic/'
    tags: [ 'controller.service_arguments' ]

  Trollfjord\Bundle\GlossaryBundle\Repository\:
    resource: '../../Repository/'
    tags: [ 'doctrine.repository_service' ]


  Trollfjord\Bundle\GlossaryBundle\TemplateEngine\Element\Glossary:
    shared: false
    public: true
    tags: [ 'content_tree.template_engine.element' ]

  Trollfjord\Bundle\GlossaryBundle\ControllerPublic\IndexController:
    arguments:
      - '%glossary.index_template%'
      - '%glossary.items_per_page_front%'

  Trollfjord\Bundle\GlossaryBundle\Controller\IndexController:
    arguments:
      - '%glossary.items_per_page%'

  glossary_service:
    class: Trollfjord\Bundle\GlossaryBundle\Service\GlossaryService
    arguments:
      - '@glossary.service_regex'

  Trollfjord\Bundle\GlossaryBundle\Service\SlugifyService: ~

  glossary.service_regex:
    class: Trollfjord\Bundle\GlossaryBundle\Service\RegexService
    public: true
    arguments:
      - '%glossary.twig_template_regex%'

  Trollfjord\Bundle\GlossaryBundle\Service\RegexService: '@glossary.service_regex'
  Trollfjord\Bundle\GlossaryBundle\Service\GlossaryService: '@glossary_service'

